# **Data**

# Covid Worry dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

covidworry_train_csv_path = '/content/drive/My Drive/Colab Notebooks/NLP Augmentation/Datasets/covidworry/covidworry_train.csv'
covidworry_dev_csv_path = '/content/drive/My Drive/Colab Notebooks/NLP Augmentation/Datasets/covidworry/covidworry_test.csv'

covidworry_train = pd.read_csv(covidworry_train_csv_path)
covidworry_dev = pd.read_csv(covidworry_dev_csv_path)


In [ ]:
print('covidworry_train shape:', covidworry_train.shape)
covidworry_train['essay'].head(10)

covidworry_train shape: (1685, 2)


0    I feel stressed because of self isolation and ...
1    At this moment, I am feeling incredibly bored ...
2    Im feeling a combination of anxiety and fear f...
3    Extremely anxious at the Unknown’s in the whol...
4    I feel worried for my friends and family and s...
5    I am worried about family and friends being af...
6    I am scared for my family and friends. I do no...
7    It's a slightly worrying situation especially ...
8    I am quite anxious at the moment as I have a p...
9    Very worried I might get it if go out for supp...
Name: essay, dtype: object

In [ ]:
covidworry_train['emotion'].head(10)

0    3
1    0
2    3
3    3
4    1
5    0
6    0
7    1
8    3
9    4
Name: emotion, dtype: int64

In [ ]:
X_train = covidworry_train['essay']
y_train = covidworry_train['emotion']

X_test = covidworry_dev['essay']
y_test = covidworry_dev['emotion']

In [ ]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1685,)
(1685,)
(723,)
(723,)


In [ ]:
# label: 'sadness': 0, 'neutral': 6, 'fear': 2, 'anger': 3, 'disgust': 4, 'surprise': 5, 'joy': 6
y_train.value_counts()

3    966
4    250
1    233
0    161
2     75
Name: emotion, dtype: int64

In [ ]:
y_test.value_counts()

3    415
4    107
1    100
0     69
2     32
Name: emotion, dtype: int64

# **Model**


In [ ]:
# Fit and transform X_train using Tfidf Vectorizer with default parameters
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train).toarray()
print('tfidf train shape:', X_train_tfidf.shape)
print('tfidf train type:', X_train_tfidf.dtype)

X_test_tfidf = vectorizer.transform(X_test).toarray()
print('tfidf test:', X_test_tfidf.shape)


tfidf train shape: (1685, 7142)
tfidf train type: float64
tfidf test: (723, 7142)


In [ ]:
from sklearn.svm import LinearSVC
clf = LinearSVC().fit(X_train_tfidf, y_train)

from sklearn import metrics
predicted = clf.predict(X_test_tfidf)

acc = metrics.accuracy_score(y_test, predicted)
print('accuracy is: ', acc*100)

from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predicted))
print('\n')
print(classification_report(y_test,predicted))

accuracy is:  56.984785615491006
[[  6   5   0  51   7]
 [  2  26   0  64   8]
 [  1   6   0  20   5]
 [ 10  21   0 368  16]
 [  1   8   0  86  12]]


              precision    recall  f1-score   support

           0       0.30      0.09      0.13        69
           1       0.39      0.26      0.31       100
           2       0.00      0.00      0.00        32
           3       0.62      0.89      0.73       415
           4       0.25      0.11      0.15       107

    accuracy                           0.57       723
   macro avg       0.31      0.27      0.27       723
weighted avg       0.48      0.57      0.50       723



/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from tqdm.notebook import tqdm
tqdm.pandas()

data = {'text': X_train, 'label': y_train}
base_train = pd.DataFrame.from_dict(data)
base_train.shape

(1685, 2)

In [ ]:
base_train.shape

(1685, 2)

# ChatGPT API Augmentation test

In [ ]:
!pip install --upgrade setuptools


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 12.5 MB/s eta 0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 57.4.0
    Uninstalling setuptools-57.4.0:
      Successfully uninstalled setuptools-57.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
cvxpy 1.2.3 requires setuptools<=64.0.2, but you have setuptools 67.6.0 which is incompatible.


In [ ]:
!pip install openai


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 KB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 19.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 13.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.2/199.2 KB 19.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 18.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 10.7 MB/s eta 0:00:00
  Created wheel for openai: filename=openai-0.27.1-py3-none-any.whl size=70091 sha256=0f447150b87b442b2e407a079d9fb01eb48d08f155d1f1e004dbb6b533a33b59
  Stored in directory: /root/.cache/pip/wheels/1f/d1/75/8015df8f7ec8ba5422d8a45786cbb64d4

In [ ]:
rep = 5
chatgpt_train = base_train.copy()

In [ ]:
import openai
import pandas as pd
import time

openai.api_key = "REPLACE WITH SECRET API KEY"

def augment_text(text):

    prompt = (f"Paraphrase this sentence: '{text}'. "
          "Your paraphrased version should be grammatically correct and semantically equivalent.")
    
    response = openai.Completion.create(
        engine="text-davinci-002",
        prompt=prompt,
        max_tokens=60,
        n=5,
        stop=None,
        temperature=0.7,
    )

    responses = []
    for i in range(5):
      responses.append(response.choices[i].text.strip())
    time.sleep(3)
    return responses



In [ ]:
chatgpt_train['paraphrase'] = chatgpt_train['text'].progress_apply(lambda x:augment_text(x))
chatgpt_train = chatgpt_train.explode('paraphrase').reset_index(drop=True)



  0%|          | 0/1685 [00:00<?, ?it/s]

In [ ]:
chatgpt_train.head(50)

text  label  \
0   I feel stressed because of self isolation and ...      3   
1   I feel stressed because of self isolation and ...      3   
2   I feel stressed because of self isolation and ...      3   
3   I feel stressed because of self isolation and ...      3   
4   I feel stressed because of self isolation and ...      3   
5   At this moment, I am feeling incredibly bored ...      0   
6   At this moment, I am feeling incredibly bored ...      0   
7   At this moment, I am feeling incredibly bored ...      0   
8   At this moment, I am feeling incredibly bored ...      0   
9   At this moment, I am feeling incredibly bored ...      0   
10  Im feeling a combination of anxiety and fear f...      3   
11  Im feeling a combination of anxiety and fear f...      3   
12  Im feeling a combination of anxiety and fear f...      3   
13  Im feeling a combination of anxiety and fear f...      3   
14  Im feeling a combination of anxiety and fear f...      3   
15  Extremely anxious at the Unknown’s in the whol...      3   
16  Extremely anxious at the Unknown’s in the whol...      3   
17  Extremely anxious at the Unknown’s in the whol...      3   
18  Extremely anxious at the Unknown’s in the whol...      3   
19  Extremely anxious at the Unknown’s in the whol...      3   
20  I feel worried for my friends and family and s...      1   
21  I feel worried for my friends and family and s...      1   
22  I feel worried for my friends and family and s...      1   
23  I feel worried for my friends and family and s...      1   
24  I feel worried for my friends and family and s...      1   
25  I am worried about family and friends being af...      0   
26  I am worried about family and friends being af...      0   
27  I am worried about family and friends being af...      0   
28  I am worried about family and friends being af...      0   
29  I am worried about family and friends being af...      0   
30  I am scared for my family and friends. I do no...      0   
31  I am scared for my family and friends. I do no...      0   
32  I am scared for my family and friends. I do no...      0   
33  I am scared for my family and friends. I do no...      0   
34  I am scared for my family and friends. I do no...      0   
35  It's a slightly worrying situation especially ...      1   
36  It's a slightly worrying situation especially ...      1   
37  It's a slightly worrying situation especially ...      1   
38  It's a slightly worrying situation especially ...      1   
39  It's a slightly worrying situation especially ...      1   
40  I am quite anxious at the moment as I have a p...      3   
41  I am quite anxious at the moment as I have a p...      3   
42  I am quite anxious at the moment as I have a p...      3   
43  I am quite anxious at the moment as I have a p...      3   
44  I am quite anxious at the moment as I have a p...      3   
45  Very worried I might get it if go out for supp...      4   
46  Very worried I might get it if go out for supp...      4   
47  Very worried I might get it if go out for supp...      4   
48  Very worried I might get it if go out for supp...      4   
49  Very worried I might get it if go out for supp...      4   

                                           paraphrase  
0   I feel stressed because of self-isolation and ...  
1   I feel stressed because of self-isolation and ...  
2   I'm feeling stressed because of self-isolation...  
3   I feel stressed because of self-isolation and ...  
4   I'm feeling stressed out because of self-isola...  
5   I am feeling very bored by the current situati...  
6   At this moment, I am feeling incredibly bored ...  
7   I'm feeling really bored right now with the co...  
8   I am currently feeling very bored by the const...  
9   I am feeling incredibly bored and alone due to...  
10  I feel a combination of anxiety and fear for m...  
11  I'm feeling a combination of anxiety and fear ...  
12  I feel a combination of anxiety and fear for m...  


# Model with augmented train data (paraphrased data)

In [ ]:
# Fit and transform X_train using Tfidf Vectorizer with default parameters
from sklearn.feature_extraction.text import TfidfVectorizer

# !! we should concatenate original train with paraphrased train
new_data = X_train.append(chatgpt_train['paraphrase'])

vectorizer = TfidfVectorizer() #max_features=3000)
X_train_tfidf = vectorizer.fit_transform(new_data).toarray() #chatgpt_train['paraphrase']).toarray()
print('tfidf train shape:', X_train_tfidf.shape)
print('tfidf train type:', X_train_tfidf.dtype)

X_test_tfidf = vectorizer.transform(X_test).toarray()
print('tfidf test:', X_test_tfidf.shape)

tfidf train shape: (10110, 7535)
tfidf train type: float64
tfidf test: (723, 7535)


In [ ]:
from sklearn.svm import LinearSVC

# !! we should concatenate original labels with paraphrased text labels
new_labels = y_train.append(chatgpt_train['label'])

clf = LinearSVC().fit(X_train_tfidf, new_labels) # chatgpt_train['label'])

from sklearn import metrics
predicted = clf.predict(X_test_tfidf)

acc = metrics.accuracy_score(y_test, predicted)
print('accuracy is: ', acc*100)

from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,predicted))
print('\n')
print(classification_report(y_test,predicted))

accuracy is:  55.87828492392808
[[ 13   8   1  38   9]
 [  3  37   0  52   8]
 [  2   6   2  19   3]
 [ 19  24   6 334  32]
 [ 10   9   1  69  18]]


              precision    recall  f1-score   support

           0       0.28      0.19      0.22        69
           1       0.44      0.37      0.40       100
           2       0.20      0.06      0.10        32
           3       0.65      0.80      0.72       415
           4       0.26      0.17      0.20       107

    accuracy                           0.56       723
   macro avg       0.37      0.32      0.33       723
weighted avg       0.51      0.56      0.52       723



In [ ]:
!cd '/content/drive/My Drive/Colab Notebooks/NLP Augmentation/Datasets/'
chatgpt_train.to_csv('/content/drive/My Drive/Colab Notebooks/NLP Augmentation/Datasets/covidworry_chatgptaug_5.csv', encoding='utf-8', index=False, sep=',')